# Uncomment this line to define a global platform for your project
 platform :osx, '10.10'

target 'XCWallpaper' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XCWallpaper
 pod 'AFNetworking'
 pod 'SDWebImage', '~> 4.0.0'
 pod 'CocoaSecurity'
 pod 'MJExtension'
end
